// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"cloud.google.com/go/civil"
)

type Record struct {
	User   string     `json:"user"`
	Date   civil.Date `json:"date"`
	Scores *Scores    `json:"scores"`
	Reason *string    `json:"reason,omitempty"`
}

type Scores struct {
	Live  int `json:"live"`
	Laugh int `json:"laugh"`
	Love  int `json:"love"`
}
